### ISSUE TITLE
This code is proprietary without a license

### ISSUE THREAD

**Issue by SpamapS** [mpahuja/mocha-elk-reporter#4]
You have failed to provide any evidence that this code is licensed as open source. As such, it would be copyright infringement for anyone to use this library.

Perhaps that isn't what you intended. Please add a LICENSE or COPYING file, and license headers to all source code files to make it clear. 

https://choosealicense.com/

**Comment by mpahuja** [comment]
Fixed by this: https://github.com/mpahuja/mocha-elk-reporter/pull/7
