### ISSUE TITLE
How to use it with Elastic Cloud

### ISSUE THREAD

**Issue by miasdaddy** [mpahuja/mocha-elk-reporter#6]
Hi, how to configure to use with Elastic Cloud? Is their anyway to specify the credentials?

**Comment by mpahuja** [comment]
Currently this module supports only no auth which can configured in the elk-reporter.js file but for other auth the support would needed to be added in the index.js. PRs are welcome :)

**Comment by ounis** [comment]
I think https://github.com/mpahuja/mocha-elk-reporter/pull/13 fixes this issue too right?

**Comment by mpahuja** [comment]
Version 2.1.0 has this feature now. Thanks to https://github.com/mpahuja/mocha-elk-reporter/pull/13. Will also update the Readme with details
